"""empty message

Revision ID: 50afa373a533
Revises: fab7d313b6de
Create Date: 2024-07-23 05:32:20.337816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50afa373a533'
down_revision = 'fab7d313b6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file', sa.String(length=200), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcription')
    # ### end Alembic commands ###
